import { fugaz } from "@/utils/appFonts";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Foodly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header: React.ReactNode = (
    <header className='p-4 sm:p-8 items-center justify-between gap-4'>
      <h1
        className={`text-base sm:text-xl md:text-xl textGradient ${fugaz.className}`}
      >
        Moodly
      </h1>
    </header>
  );
  const footer: React.ReactNode = (
    <footer className='p-4 sm:p-8'>footer</footer>
  );
  return (
    <html lang='en'>
      <body
        className={`w-full w-max-[1000px] mx-auto text-sm sm:text-base min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
